# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty

permalink: blogpost/:title/

# Setup
title: 'Sahil Dhar'
tagline: 'I write about Application Security and Research here :)'
description: 'Application Security and Exploitation all day everyday. Offensive Security Certified Expert.'
baseurl: ''
paginate: 2

# About/contact
author:
  name:         Sahil Dhar
  twitter:      https://twitter.com/0x401



highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge