# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty

permalink: blogpost/:title/

# Setup
title: 'Sahil Dhar'
tagline: 'Application Security and Exploitation all day everyday.'
description: 'This my personal research blog. Any content posted here, strictly does not represent the views/opinions of my current/past employer.'
baseurl: ''
paginate: 2

# About/contact
author:
  name:         Sahil Dhar
  twitter:      https://twitter.com/0x401



highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge